-- MySQL Script generated by MySQL Workbench
-- 06/04/17 10:06:52
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema meituan
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `meituan` ;

-- -----------------------------------------------------
-- Schema meituan
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `meituan` DEFAULT CHARACTER SET utf8 ;
USE `meituan` ;

-- -----------------------------------------------------
-- Table `meituan`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `meituan`.`users` ;

CREATE TABLE IF NOT EXISTS `meituan`.`users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `mobile` VARCHAR(20) NOT NULL,
  `username` VARCHAR(45) NULL DEFAULT NULL,
  `birthday` VARCHAR(10) NULL DEFAULT NULL,
  `password` VARCHAR(100) NOT NULL,
  `token` VARCHAR(255) NULL DEFAULT NULL,
  `createtime` DATETIME NULL DEFAULT NULL,
  `updatetime` DATETIME NULL DEFAULT NULL,
  `avatar` VARCHAR(200) NULL DEFAULT NULL,
  `status` TINYINT(4) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `mobile_UNIQUE` (`mobile` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `meituan`.`deliveries`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `meituan`.`deliveries` ;

CREATE TABLE IF NOT EXISTS `meituan`.`deliveries` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `consignee` VARCHAR(45) NOT NULL,
  `tel` VARCHAR(20) NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  `area` VARCHAR(45) NOT NULL,
  `zipcode` INT(10) NOT NULL,
  `selected` TINYINT(1) NOT NULL DEFAULT '0',
  `createtime` DATETIME NULL DEFAULT NULL,
  `updatetime` DATETIME NULL DEFAULT NULL,
  `users_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_deliveries_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_deliveries_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `meituan`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `meituan`.`sellers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `meituan`.`sellers` ;

CREATE TABLE IF NOT EXISTS `meituan`.`sellers` (
  `id` INT(11) NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `description` VARCHAR(45) NULL DEFAULT NULL,
  `delivery_time` INT(11) NULL DEFAULT NULL,
  `score` FLOAT NULL DEFAULT NULL,
  `service_score` FLOAT NULL DEFAULT NULL,
  `food_score` FLOAT NULL DEFAULT NULL,
  `rank_rate` FLOAT NULL DEFAULT NULL,
  `min_price` DOUBLE NULL DEFAULT NULL,
  `delivery_price` DOUBLE NULL DEFAULT NULL,
  `bulletin` LONGTEXT NULL DEFAULT NULL,
  `avatar` VARCHAR(200) NULL DEFAULT NULL,
  `sellercol` VARCHAR(45) NULL DEFAULT NULL,
  `address` VARCHAR(200) NULL DEFAULT NULL,
  `mobile` VARCHAR(20) NULL DEFAULT NULL,
  `dist_info` VARCHAR(45) NULL DEFAULT NULL,
  `dist_start_time` VARCHAR(20) NULL DEFAULT NULL,
  `dist_end_time` VARCHAR(20) NULL DEFAULT NULL,
  `createtime` DATETIME NULL DEFAULT NULL,
  `updatetime` DATETIME NULL DEFAULT NULL,
  `status` TINYINT(4) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `meituan`.`food_categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `meituan`.`food_categories` ;

CREATE TABLE IF NOT EXISTS `meituan`.`food_categories` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `seller_id` INT(11) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `support_id` INT(11) NOT NULL DEFAULT '-1',
  `createtime` DATETIME NULL DEFAULT NULL,
  `updatetime` DATETIME NULL DEFAULT NULL,
  `status` TINYINT(4) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  INDEX `fk_food_category_sellers1_idx` (`seller_id` ASC),
  CONSTRAINT `fk_food_category_sellers1`
    FOREIGN KEY (`seller_id`)
    REFERENCES `meituan`.`sellers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 17
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `meituan`.`foods`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `meituan`.`foods` ;

CREATE TABLE IF NOT EXISTS `meituan`.`foods` (
  `id` INT(11) NOT NULL,
  `seller_id` INT(11) NOT NULL,
  `name` VARCHAR(120) NOT NULL,
  `price` DOUBLE NOT NULL,
  `old_price` DOUBLE NULL DEFAULT NULL,
  `description` VARCHAR(200) NULL DEFAULT NULL,
  `sell_count` INT(11) NULL DEFAULT NULL,
  `info` VARCHAR(200) NULL DEFAULT NULL,
  `image` VARCHAR(200) NULL DEFAULT NULL,
  `createtime` DATETIME NULL DEFAULT NULL,
  `updatetime` DATETIME NULL DEFAULT NULL,
  `status` TINYINT(4) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  INDEX `fk_foods_sellers1_idx` (`seller_id` ASC),
  CONSTRAINT `fk_foods_sellers1`
    FOREIGN KEY (`seller_id`)
    REFERENCES `meituan`.`sellers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `meituan`.`food_categories__foods`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `meituan`.`food_categories__foods` ;

CREATE TABLE IF NOT EXISTS `meituan`.`food_categories__foods` (
  `foods_id` INT(11) NOT NULL,
  `food_categories_id` INT(11) NOT NULL,
  PRIMARY KEY (`foods_id`, `food_categories_id`),
  INDEX `fk_food_categories__foods_food_categories1_idx1` (`food_categories_id` ASC),
  CONSTRAINT `fk_food_categories__foods_foods3`
    FOREIGN KEY (`foods_id`)
    REFERENCES `meituan`.`foods` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_food_categories__foods_food_categories1`
    FOREIGN KEY (`food_categories_id`)
    REFERENCES `meituan`.`food_categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `meituan`.`pics`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `meituan`.`pics` ;

CREATE TABLE IF NOT EXISTS `meituan`.`pics` (
  `id` INT(11) NOT NULL,
  `url` VARCHAR(200) NOT NULL,
  `createtime` VARCHAR(45) NOT NULL,
  `status` TINYINT(4) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `meituan`.`food_pic`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `meituan`.`food_pic` ;

CREATE TABLE IF NOT EXISTS `meituan`.`food_pic` (
  `food_id` INT(11) NOT NULL,
  `pic_id` INT(11) NOT NULL,
  INDEX `fk_food_pic_foods1_idx` (`food_id` ASC),
  INDEX `fk_food_pic_pics1_idx` (`pic_id` ASC),
  CONSTRAINT `fk_food_pic_foods1`
    FOREIGN KEY (`food_id`)
    REFERENCES `meituan`.`foods` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_food_pic_pics1`
    FOREIGN KEY (`pic_id`)
    REFERENCES `meituan`.`pics` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `meituan`.`food_ratings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `meituan`.`food_ratings` ;

CREATE TABLE IF NOT EXISTS `meituan`.`food_ratings` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `seller_id` INT(11) NOT NULL,
  `user_id` INT(11) NOT NULL,
  `food_id` INT(11) NOT NULL,
  `rate_time` VARCHAR(20) NULL DEFAULT NULL,
  `delivery_time` VARCHAR(10) NULL DEFAULT NULL,
  `score` INT(1) NULL DEFAULT NULL,
  `rate_type` TINYINT(1) NULL DEFAULT NULL COMMENT '点赞：（点赞1，不点0）',
  `text` VARCHAR(300) NULL DEFAULT NULL,
  `status` TINYINT(4) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  INDEX `id_idx` (`user_id` ASC),
  INDEX `food_id_idx` (`food_id` ASC),
  INDEX `seller_id` (`seller_id` ASC),
  CONSTRAINT `food_id`
    FOREIGN KEY (`food_id`)
    REFERENCES `meituan`.`foods` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `seller_id`
    FOREIGN KEY (`seller_id`)
    REFERENCES `meituan`.`sellers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `meituan`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `meituan`.`supports`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `meituan`.`supports` ;

CREATE TABLE IF NOT EXISTS `meituan`.`supports` (
  `id` INT(11) NOT NULL,
  `type` TINYINT(2) NOT NULL,
  `seller_id` INT(11) NOT NULL,
  `description` VARCHAR(200) NOT NULL,
  `createtime` DATETIME NULL DEFAULT NULL,
  `updatetime` DATETIME NULL DEFAULT NULL,
  `status` TINYINT(4) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  INDEX `fk_supports_sellers1_idx` (`seller_id` ASC),
  CONSTRAINT `fk_supports_sellers1`
    FOREIGN KEY (`seller_id`)
    REFERENCES `meituan`.`sellers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
