-- MySQL Script generated by MySQL Workbench
-- 04/23/17 14:11:52
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema meituan
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `meituan` ;

-- -----------------------------------------------------
-- Schema meituan
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `meituan` DEFAULT CHARACTER SET utf8 ;
USE `meituan` ;

-- -----------------------------------------------------
-- Table `meituan`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `meituan`.`users` ;

CREATE TABLE IF NOT EXISTS `meituan`.`users` (
  `id` INT NOT NULL,
  `mobile` VARCHAR(20) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `token` VARCHAR(255) NULL,
  `createtime` DATETIME NULL,
  `updatetime` DATETIME NULL,
  `avatar` VARCHAR(200) NULL,
  `status` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `mobile_UNIQUE` (`mobile` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `meituan`.`sellers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `meituan`.`sellers` ;

CREATE TABLE IF NOT EXISTS `meituan`.`sellers` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  `delivery_time` INT NULL,
  `score` FLOAT NULL,
  `service_score` FLOAT NULL,
  `food_score` FLOAT NULL,
  `rank_rate` FLOAT NULL,
  `min_price` DOUBLE NULL,
  `delivery_price` DOUBLE NULL,
  `bulletin` LONGTEXT NULL,
  `avatar` VARCHAR(200) NULL,
  `sellercol` VARCHAR(45) NULL,
  `address` VARCHAR(200) NULL,
  `mobile` VARCHAR(20) NULL,
  `dist_info` VARCHAR(45) NULL,
  `dist_start_time` VARCHAR(20) NULL,
  `dist_end_time` VARCHAR(20) NULL,
  `createtime` DATETIME NULL,
  `updatetime` DATETIME NULL,
  `status` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `meituan`.`foods`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `meituan`.`foods` ;

CREATE TABLE IF NOT EXISTS `meituan`.`foods` (
  `id` INT NOT NULL,
  `seller_id` INT NOT NULL,
  `name` VARCHAR(120) NOT NULL,
  `price` DOUBLE NOT NULL,
  `old_price` DOUBLE NULL,
  `description` VARCHAR(200) NULL,
  `sell_count` INT NULL,
  `info` VARCHAR(200) NULL,
  `image` VARCHAR(200) NULL,
  `createtime` DATETIME NULL,
  `updatetime` DATETIME NULL,
  `status` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  INDEX `fk_foods_sellers1_idx` (`seller_id` ASC),
  CONSTRAINT `fk_foods_sellers1`
    FOREIGN KEY (`seller_id`)
    REFERENCES `meituan`.`sellers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `meituan`.`food_categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `meituan`.`food_categories` ;

CREATE TABLE IF NOT EXISTS `meituan`.`food_categories` (
  `id` INT NOT NULL,
  `seller_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `support_id` INT NOT NULL DEFAULT -1,
  `createtime` DATETIME NULL,
  `updatetime` DATETIME NULL,
  `status` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  INDEX `fk_food_category_sellers1_idx` (`seller_id` ASC),
  CONSTRAINT `fk_food_category_sellers1`
    FOREIGN KEY (`seller_id`)
    REFERENCES `meituan`.`sellers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `meituan`.`supports`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `meituan`.`supports` ;

CREATE TABLE IF NOT EXISTS `meituan`.`supports` (
  `id` INT NOT NULL,
  `seller_id` INT NULL,
  `description` VARCHAR(200) NOT NULL,
  `createtime` DATETIME NULL,
  `updatetime` DATETIME NULL,
  `status` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  INDEX `fk_supports_sellers1_idx` (`seller_id` ASC),
  CONSTRAINT `fk_supports_sellers1`
    FOREIGN KEY (`seller_id`)
    REFERENCES `meituan`.`sellers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `meituan`.`ratings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `meituan`.`ratings` ;

CREATE TABLE IF NOT EXISTS `meituan`.`ratings` (
  `id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `food_id` INT NOT NULL,
  `rate_time` VARCHAR(20) NULL,
  `delivery_time` VARCHAR(10) NULL,
  `score` FLOAT NULL,
  `rate_type` TINYINT(1) NULL,
  `text` VARCHAR(300) NULL,
  `status` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  INDEX `id_idx` (`user_id` ASC),
  INDEX `food_id_idx` (`food_id` ASC),
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `meituan`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `food_id`
    FOREIGN KEY (`food_id`)
    REFERENCES `meituan`.`foods` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `meituan`.`pics`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `meituan`.`pics` ;

CREATE TABLE IF NOT EXISTS `meituan`.`pics` (
  `id` INT NOT NULL,
  `url` VARCHAR(200) NOT NULL,
  `createtime` VARCHAR(45) NOT NULL,
  `status` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `meituan`.`food_categories__foods`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `meituan`.`food_categories__foods` ;

CREATE TABLE IF NOT EXISTS `meituan`.`food_categories__foods` (
  `food_id` INT NULL,
  `cate_id` INT NULL,
  INDEX `fk_food_categories__foods_food_categories1_idx` (`cate_id` ASC),
  INDEX `fk_food_categories__foods_foods1_idx` (`food_id` ASC),
  CONSTRAINT `fk_food_categories__foods_food_categories1`
    FOREIGN KEY (`cate_id`)
    REFERENCES `meituan`.`food_categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_food_categories__foods_foods1`
    FOREIGN KEY (`food_id`)
    REFERENCES `meituan`.`foods` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `meituan`.`food_pic`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `meituan`.`food_pic` ;

CREATE TABLE IF NOT EXISTS `meituan`.`food_pic` (
  `food_id` INT NOT NULL,
  `pic_id` INT NOT NULL,
  INDEX `fk_food_pic_foods1_idx` (`food_id` ASC),
  INDEX `fk_food_pic_pics1_idx` (`pic_id` ASC),
  CONSTRAINT `fk_food_pic_foods1`
    FOREIGN KEY (`food_id`)
    REFERENCES `meituan`.`foods` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_food_pic_pics1`
    FOREIGN KEY (`pic_id`)
    REFERENCES `meituan`.`pics` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
